"""Static title → category mapping for catalog variants (vwt.33).

The pipeline writes one ``variants`` row per dish; the ``category`` column
backs the PWA's category dropdown. Source for the mapping is the
L1-normalized title (e.g. ``"chicken pot pie"``, ``"pumpkin bread"``).
``categorize`` walks an ordered keyword-rule list and returns the first
hit, or ``None`` if no rule matches.

Static mapping over an LLM call by design: 38k variants × one prompt is
expensive and non-deterministic, while a 250-line rule table covers the
vast majority of L1 titles correctly and is trivially reviewable. When
new L1 groups appear that aren't covered, add a keyword rather than
threading another LLM step through the pipeline.

Rule ordering matters. High-specificity overrides come first
(``"bread pudding"`` → dessert, ahead of plain ``"bread"`` → bread),
then soup/salad, then main-dish phrases (``"pot pie"`` ahead of
``"pie"``), sauces/condiments, appetizers, bread, breakfast, dessert,
and finally side dishes as the loosest catch-all.
"""

from __future__ import annotations

import re

CATEGORIES: tuple[str, ...] = (
    "appetizer",
    "beverage",
    "bread",
    "breakfast",
    "condiment",
    "dessert",
    "main",
    "salad",
    "sauce",
    "side",
    "soup",
)
"""Frozen list of category labels written by ``categorize``.

Stable enum-ish set so PWA tests and category-dropdown unit tests can
assert on a fixed vocabulary. Adding a new label here requires also
updating PWA expectations.
"""


# Each tuple: (category, keywords). Walked in order; first whole-word
# match against the title wins. Keywords are matched with \b boundaries
# so "pie" matches "apple pie" but not "pies" — pluralized forms are
# enumerated explicitly to keep the table reviewable.
_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    # --- Specific-phrase overrides ahead of generic categories --------
    # Sweet "pizza" / sweet baked things that look savory by token.
    (
        "dessert",
        (
            "fruit pizza",
            "dessert pizza",
            "cookie pizza",
            "candy pizza",
        ),
    ),
    # Pizza/pie crusts and doughs are bread, not the parent main dish.
    (
        "bread",
        (
            "pizza dough",
            "pizza crust",
            "pie crust",
            "pie crusts",
            "tart shell",
            "tart shells",
            "pastry crust",
            "graham crust",
            "graham cracker crust",
        ),
    ),
    # "X sauce" must override main's grab on words like "barbecue",
    # "spaghetti", "pizza" so the table sauce doesn't get filed under
    # the dish it accompanies.
    (
        "sauce",
        (
            "barbecue sauce",
            "bbq sauce",
            "spaghetti sauce",
            "pizza sauce",
            "enchilada sauce",
            "taco sauce",
            "marinara sauce",
            "alfredo sauce",
            "fudge sauce",
            "chocolate sauce",
            "caramel sauce",
            "butterscotch sauce",
            "raspberry sauce",
            "blueberry sauce",
            "strawberry sauce",
            "cranberry sauce",
        ),
    ),
    # Sweet puddings: "bread pudding" must beat "bread"; "rice pudding"
    # must beat "rice" (side); etc. Also catches "X roll" desserts so
    # they don't fall through to bread's "rolls" or get miscategorized
    # by the side/dessert catch-all.
    (
        "dessert",
        (
            "bread pudding",
            "rice pudding",
            "banana pudding",
            "tapioca pudding",
            "chocolate pudding",
            "vanilla pudding",
            "lemon pudding",
            "date pudding",
            "persimmon pudding",
            "brownie pudding",
            "hot fudge pudding",
            "dirt pudding",
            "noodle pudding",
            "pumpkin roll",
            "jelly roll",
            "cake roll",
            "swiss roll",
            "ice cream roll",
            "ice cream cake",
            "cookie roll",
        ),
    ),
    # Savory dishes that resemble a dessert by name. Pre-empts the
    # later dessert catch-all (squares, etc.).
    (
        "appetizer",
        (
            "spinach squares",
            "zucchini appetizers",
        ),
    ),
    # Savory "puddings"/breads that look dessert-shaped but aren't,
    # plus regional sides (copper pennies, harvard beets, fried green
    # tomatoes, baked pineapple) that lack obvious side-pointing tokens.
    (
        "side",
        (
            "yorkshire pudding",
            "corn pudding",
            "sweet potato pudding",
            "spoon bread",
            "copper pennies",
            "copper penny carrots",
            "harvard beets",
            "fried green tomatoes",
            "baked pineapple",
            "scalloped pineapple",
            "glazed carrots",
            "marinated carrots",
            "candied sweet potatoes",
            "candied yams",
            "scalloped corn",
            "scalloped potatoes",
            "scalloped tomatoes",
            "scalloped oysters",
            "creamed corn",
            "creamed spinach",
            "creamed peas",
            "green rice",
            "spanish rice",
            "brown rice",
            "wild rice",
            "dirty rice",
            "red beans and rice",
        ),
    ),
    # Meat-bearing "pies" go to main, not dessert.
    (
        "main",
        (
            "pot pie",
            "pot pies",
            "shepherd pie",
            "shepherd's pie",
            "shepherds pie",
            "cottage pie",
            "tamale pie",
            "tortilla pie",
            "taco pie",
            "hamburger pie",
            "cheeseburger pie",
            "tomato pie",
            "spaghetti pie",
            "zucchini pie",
            "pizza pie",
            "onion pie",
            "vidalia onion pie",
        ),
    ),
    # --- Beverages -----------------------------------------------------
    (
        "beverage",
        (
            "punch",
            "tea",
            "lemonade",
            "smoothie",
            "julius",
            "eggnog",
            "egg nog",
            "wassail",
            "kahlua",
            "cocoa",
            "cider",
            "milkshake",
            "shake",
            "sangria",
            "margarita",
            "spiced tea",
            "russian tea",
            "fruit punch",
            "banana punch",
            "party punch",
            "hot buttered rum",
            "fruit slush",
            "slush",
            "frappe",
            "milk punch",
            "iced coffee",
            "hot chocolate",
            "hot chocolate mix",
            "hot cocoa",
            "chocolate milk",
            "lemonade",
        ),
    ),
    # --- Soups / stews / chili ----------------------------------------
    (
        "soup",
        (
            "soup",
            "chowder",
            "bisque",
            "stew",
            "chili",
            "gumbo",
            "gazpacho",
            "borscht",
        ),
    ),
    # --- Salads & slaws -----------------------------------------------
    # Note: "chicken salad" lands here (US convention treats it as a
    # salad). Same for "tuna salad", "ham salad", etc.
    (
        "salad",
        (
            "salad",
            "slaw",
            "coleslaw",
            "cole slaw",
            "tabbouleh",
            "tabouli",
            "wilted lettuce",
        ),
    ),
    # --- Main dishes --------------------------------------------------
    # Broad: pasta, casseroles, meat dishes, pizza. Earlier than dessert
    # so "chicken spaghetti" doesn't drift toward "spaghetti pie" rules.
    (
        "main",
        (
            # Pasta
            "lasagna",
            "lasagne",
            "manicotti",
            "ravioli",
            "tortellini",
            "spaghetti",
            "fettuccine",
            "fettucini",
            "alfredo",
            "carbonara",
            "ziti",
            "macaroni and cheese",
            "macaroni cheese",
            "mac and cheese",
            "tetrazzini",
            "parmigiana",
            "parmesan",  # chicken/eggplant parmesan
            "cannelloni",
            "rigatoni",
            "penne",
            # Mexican mains
            "enchilada",
            "enchiladas",
            "fajita",
            "fajitas",
            "burrito",
            "tamale",
            "chimichanga",
            "quesadilla",
            "taco",
            "tacos",
            # Casseroles & one-pots
            "casserole",
            "stroganoff",
            "jambalaya",
            "paella",
            "risotto",
            "fried rice",
            "goulash",
            "moussaka",
            "ratatouille",
            "tetrazzini",
            # Meat-based phrasings
            "meatloaf",
            "meat loaf",
            "meatballs",
            "meat balls",
            "sloppy joes",
            "sloppy joe",
            "salisbury steak",
            "swiss steak",
            "pepper steak",
            "pepper steaks",
            "swedish meatballs",
            "porcupine meatballs",
            "porcupine meat balls",
            "stuffed peppers",
            "stuffed green peppers",
            "stuffed cabbage",
            "stuffed shells",
            "cabbage rolls",
            "salisbury",
            # Chicken
            "chicken pie",
            "chicken cordon bleu",
            "chicken kiev",
            "chicken piccata",
            "chicken cacciatore",
            "chicken divan",
            "chicken broccoli",
            "chicken and rice",
            "chicken and broccoli",
            "chicken and dumplings",
            "chicken supreme",
            "chicken a la king",
            "chicken enchilada",
            "chicken enchiladas",
            "fried chicken",
            "baked chicken",
            "roast chicken",
            "roasted chicken",
            "barbecue chicken",
            "bbq chicken",
            "lemon chicken",
            "mexican chicken",
            "king ranch chicken",
            "oven fried chicken",
            "poppy seed chicken",
            "parmesan chicken",
            "sweet and sour chicken",
            "honey chicken",
            "chicken parmesan",
            "chicken parmigiana",
            "chicken tetrazzini",
            "chicken spaghetti",
            # Beef / pork / fish
            "beef stew",
            "beef stroganoff",
            "beef barbecue",
            "beef burgundy",
            "pork chop",
            "pork chops",
            "pulled pork",
            "carnitas",
            "spareribs",
            "spare ribs",
            "ribs",
            "salmon loaf",
            "salmon patties",
            "salmon croquettes",
            "tuna noodle",
            "shrimp scampi",
            "shrimp creole",
            "shrimp newburg",
            "crab cakes",
            "fish fry",
            "fried fish",
            "ham loaf",
            "ham balls",
            "swedish meat balls",
            # Pizza
            "pizza",
            # Other
            "baked beans",
            "calico beans",
            "baked spaghetti",
            "baked ziti",
            "eggplant parmesan",
            "eggplant parmigiana",
            "fried okra",
            "fried catfish",
            "hamburger",
            "cheeseburger",
            "barbecue",  # generic enough; usually "barbecue beef/chicken"
            "bbq",
            "stir fry",
            "stir-fry",
            "texas hash",
            "sweet and sour pork",
            "sweet and sour beef",
            "chicken marsala",
            "chicken adobo",
            "chicken spectacular",
            "porcupines",
            "shipwreck",
            "poor man steak",
            "poor man's steak",
            "country fried steak",
            "chicken fried steak",
            "stroganov",
            "kebab",
            "kebabs",
            "kabob",
            "kabobs",
            "schnitzel",
            "etouffee",
            "étouffée",
            "chop suey",
            "cavatini",
            "hawaiian chicken",
            "no peek chicken",
            "honey mustard chicken",
            "chicken paprika",
            "chicken paprikash",
            "chicken nuggets",
            "tuna burgers",
            "chicken continental",
            "hobo dinner",
            "barbecued",
            "bbq",
            "beer batter",
            "pot roast",
            "chicken curry",
            "beef curry",
            "lamb curry",
            "chicken chow mein",
            "chow mein",
            "chicken divine",
            "chicken marbella",
            "chicken normandy",
            "chicken florentine",
            "stuffed bell peppers",
            "six layer dinner",
            "seven layer dinner",
            "shipwreck casserole",
            "spanakopita",
            "moussaka",
            "roast beef",
            "roast turkey",
            "roast pork",
            "roast lamb",
            "prime rib",
            "beef tenderloin",
            "pork tenderloin",
            "pork roast",
            "leg of lamb",
            "rack of lamb",
            "corned beef",
            "shrimp boil",
            "fondue",
        ),
    ),
    # --- Sauces, gravies, dressings -----------------------------------
    # Before condiments so "barbecue sauce" → sauce (it would also match
    # "barbecue" → main, but "main" was tested above and only matches
    # when a meat is also named; bare "barbecue sauce" arrives here).
    (
        "sauce",
        (
            "sauce",
            "gravy",
            "marinara",
            "salsa",
            "picante",
            "syrup",
            "glaze",
            "pesto",
            "hollandaise",
            "vinaigrette",
            "dressing",  # salad dressing — note "stuffing" goes to side
            "tzatziki",
            "tahini",
            "remoulade",
            "aioli",
            "chimichurri",
            "stock",
            "broth",
        ),
    ),
    # --- Condiments / preserves / pickles -----------------------------
    (
        "condiment",
        (
            "pickled",
            "pickles",
            "pickle",
            "relish",
            "jelly",
            "jam",
            "preserves",
            "marmalade",
            "chutney",
            "ketchup",
            "mayonnaise",
            "apple butter",
            "peanut butter",  # the spread; "peanut butter cookies" caught by dessert
            "chow chow",
            "chow-chow",
            "bread and butter pickles",
            "lemon curd",
            "fruit curd",
            "honey butter",
            "strawberry butter",
            "fruit butter",
            "pear honey",
            "pear butter",
            "apricot butter",
        ),
    ),
    # --- Appetizers / dips / party food -------------------------------
    (
        "appetizer",
        (
            "dip",
            "ball",
            "balls",
            "spread",
            "mousse",
            "pate",
            "wings",
            "deviled eggs",
            "party mix",
            "trail mix",
            "snack mix",
            "stuffed mushrooms",
            "cocktail meatballs",
            "cheese straws",
            "cheese wafers",
            "cheese puffs",
            "guacamole",
            "hummus",
            "tapenade",
            "bruschetta",
            "salsa dip",
            "rangoon",
            "rumaki",
            "bites",
            "shrimp mold",
            "spiced pecans",
            "spiced nuts",
            "sugared pecans",
            "candied nuts",
            "spiced almonds",
            "marinated mushrooms",
            "cheese krispies",
            "cheese krispie",
            "crabbies",
            "rumaki",
            "stuffed celery",
            "deviled",
            "antipasto",
            "tartlets",
            "canape",
            "canapes",
            "crostini",
            "queso",
            "ranch dip",
            "shrimp butter",
            "crab mold",
            "cheese ring",
            "cheese roll",
            "glazed pecans",
            "candied pecans",
            "spiced walnuts",
            "rolled-up sandwiches",
            "stuffed jalapenos",
            "nuts and bolts",
            "chex mix",
            "muddy buddies",
            "ham delights",
            "ham rolls",
            "salmon log",
            "salmon spread",
            "bacon wrapped",
            "bacon-wrapped",
            "water chestnuts",
            "texas caviar",
            "salsa",
            "queso fundido",
            "pinwheel sandwiches",
        ),
    ),
    # --- Bread family --------------------------------------------------
    # Sweet quick breads (banana/pumpkin/zucchini bread) land here, not
    # in dessert — same as a US grocery's bread aisle.
    (
        "bread",
        (
            "bread",
            "rolls",
            "biscuits",
            "muffins",
            "muffin",
            "cornbread",
            "corn bread",
            "scones",
            "doughnuts",
            "donuts",
            "donut",
            "doughnut",
            "bagels",
            "popovers",
            "tortillas",
            "tortilla",
            "pita",
            "pretzels",
            "pretzel",
            "fritter",
            "fritters",
            "hush puppies",
            "dumplings",
            "pizza dough",
            "pizza crust",
            "pie crust",
            "crust",
            "sourdough starter",
            "yeast",
            "loaf",  # zucchini loaf etc.
            "focaccia",
            "challah",
            "brioche",
            "ciabatta",
            "naan",
            "sticky buns",
            "buns",
            "hot cross buns",
            "monkey",  # monkey bread / monkey balls — already caught by bread/ball
            "lefse",
            "lefser",
            "biscuit mix",
            "pastry",
            "pasties",
            "spaetzle",
            "spätzle",
            "sally lunn",
            "butter dips",
            "cinnamon twists",
            "cinnamon roll",
            "cinnamon rolls",
        ),
    ),
    # --- Breakfast ----------------------------------------------------
    (
        "breakfast",
        (
            "pancakes",
            "pancake",
            "waffles",
            "waffle",
            "french toast",
            "granola",
            "cereal",
            "porridge",
            "omelet",
            "omelette",
            "frittata",
            "quiche",
            "strata",
            "breakfast",
            "crepes",
            "crepe",
            "pannkakor",
            "baked oatmeal",
            "overnight oats",
            "muesli",
            "scramble",
            "scrambled eggs",
            "huevos",
            "hash browns",
            "hash brown",
        ),
    ),
    # --- Desserts ------------------------------------------------------
    # Last broad sweep before side. Mains/breads/etc. caught above win.
    (
        "dessert",
        (
            "cake",
            "cakes",
            "cookies",
            "cookie",
            "pie",
            "pies",
            "tart",
            "tarts",
            "brownies",
            "brownie",
            "bars",
            "squares",  # lemon squares, chess squares, etc.
            "cobbler",
            "crisp",
            "crunch",
            "fudge",
            "candy",
            "candies",
            "ice cream",
            "icecream",
            "pudding",
            "custard",
            "frosting",
            "icing",
            "cheesecake",
            "baklava",
            "eclair",
            "eclairs",
            "shortbread",
            "shortcake",
            "trifle",
            "souffle",
            "soufflé",
            "macaroons",
            "macaroon",
            "snickerdoodle",
            "snickerdoodles",
            "blondies",
            "buckeyes",
            "divinity",
            "taffy",
            "toffee",
            "pralines",
            "praline",
            "brittle",
            "caramels",
            "caramel",
            "fondant",
            "marshmallow",
            "marshmallows",
            "meringue",
            "delight",
            "dessert",
            "kuchen",
            "strudel",
            "cupcakes",
            "cupcake",
            "scotcheroos",
            "scotcheroo",
            "lush",
            "yum yum",
            "sherbet",
            "sorbet",
            "popsicles",
            "popsicle",
            "jello",
            "jell-o",
            "gelatin",
            "tassies",
            "ambrosia",
            "compote",
            "mousse",
            "tiramisu",
            "flan",
            "creme brulee",
            "crème brûlée",
            "fudgesicle",
            "rugelach",
            "biscotti",
            "panna cotta",
            "tres leches",
            "petit four",
            "petit fours",
            "whoopie pies",
            "whoopie",
            "snowballs",
            "thumbprint",
            "thumbprints",
            "hermits",
            "spritz",
            "icebox cookies",
            "no bake",
            "no-bake",
            "play dough",
            "play-dough",
            "puppy chow",
            "magic bars",
            "hello dollies",
            "hello dolly",
            "dirt",
            "buttercream",
            "ganache",
            "praline",
            "pralines",
            "honey bun",
            "gingerbread",
            "gingersnaps",
            "ginger cookies",
            "ginger snaps",
            "buckle",
            "crinkles",
            "chews",
            "sandies",
            "crispies",
            "scotchies",
            "blossoms",
            "torte",
            "tortes",
            "cream puffs",
            "pecan puffs",
            "cheesecakes",
            "mini cheesecakes",
            "danish",
            "ladyfingers",
            "lady fingers",
            "cracker jacks",
            "heavenly hash",
            "bananas foster",
            "peanut patties",
            "milky way",
            "pinwheels",
            "kolache",
            "kolaches",
            "rosettes",
            "oatmeal scotchies",
            "butterhorns",
            "mississippi mud",
            "sopaipillas",
            "chocolate covered",
            "almond bark",
            "tassies",
            "apple dapple",
            "apple kuchen",
            "pumpkin squares",
            "pumpkin bars",
            "pumpkin dessert",
            "wacky cake",
            "sock it to me",
            "earthquake",
            "honey bun cake",
            "scotcheroos",
            "graham cracker",
            "bonbons",
            "bon bons",
            "almond roca",
            "peanut clusters",
            "chocolate clusters",
            "cherry winks",
            "nutty fingers",
            "pecan fingers",
            "melting moments",
            "pizzelles",
            "pizzelle",
            "beignets",
            "beignet",
            "chewies",
            "buffalo chips",
            "apple crumble",
            "fruit crumble",
            "banana split",
            "rocky road",
            "halvah",
            "halva",
            "marzipan",
            "petits fours",
            "pixies",
            "creams",  # ginger creams, etc.
            "pecan delights",
            "cherry delights",
            "cherry yum-yum",
            "cherries in the snow",
            "mints",
            "reese cups",
            "reese's cups",
            "apple slices",  # baked dessert
            "churros",
            "churro",
        ),
    ),
    # --- Side dishes (catch-all for vegetables/starches) --------------
    (
        "side",
        (
            "potato",
            "potatoes",
            "rice",
            "beans",
            "corn",
            "asparagus",
            "broccoli",
            "cauliflower",
            "zucchini",
            "squash",
            "carrots",
            "carrot",
            "peas",
            "spinach",
            "okra",
            "vegetables",
            "vegetable",
            "veggie",
            "veggies",
            "stuffing",
            "pilaf",
            "grits",
            "yams",
            "fries",
            "tots",
            "noodles",
            "dressing",  # cornbread dressing = stuffing
            "sauerkraut",
            "succotash",
            "creamed",  # creamed spinach, creamed corn
            "scalloped",  # scalloped potatoes/corn
            "au gratin",
            "twice baked",
            "twice-baked",
            "baked potato",
            "candied",  # candied yams (sweet but a side)
            "onion rings",
            "fried onions",
            "curried fruit",
            "lemon curd",
            "pico de gallo",
            "baked apples",
            "fried apples",
            "applesauce",  # often a side
            "cucumbers",
            "cucumber",
            "tomatoes",
            "tomato",
            "mushrooms",
            "mushroom",
            "onion",
            "onions",
            "leeks",
            "shipwreck",
            "succotash",
            "polenta",
            "couscous",
            "quinoa",
            "barley",
            "lentils",
            "kale",
            "chard",
            "collards",
            "skillet cabbage",
            "skillet corn",
            "green bean bundles",
            "pineapple bake",
            "escalloped pineapple",
            "colcannon",
            "gnocchi",
            "spiced peaches",
            "stewed tomatoes",
            "fried tomatoes",
        ),
    ),
)


def categorize(normalized_title: str) -> str | None:
    """Return a category label for an L1-normalized recipe title.

    ``None`` when no rule matches — callers writing the DB can pass that
    through as NULL and the PWA will render the "uncategorized" UI label.
    """
    if not normalized_title:
        return None
    title = normalized_title.lower()
    for category, keywords in _RULES:
        for kw in keywords:
            pattern = rf"\b{re.escape(kw)}\b"
            if re.search(pattern, title):
                return category
    return None
